// Generated by scripts/make_icons.py from assets/icons/walk.gif and stand.png. Do not edit by hand.
export const WALK_FRAMES: number[] = [
  require('./walk_00.png'),
  require('./walk_01.png'),
  require('./walk_02.png'),
  require('./walk_03.png'),
  require('./walk_04.png'),
  require('./walk_05.png'),
  require('./walk_06.png'),
  require('./walk_07.png'),
  require('./walk_08.png'),
  require('./walk_09.png'),
  require('./walk_10.png'),
  require('./walk_11.png'),
  require('./walk_12.png'),
  require('./walk_13.png'),
  require('./walk_14.png'),
  require('./walk_15.png'),
  require('./walk_16.png'),
  require('./walk_17.png'),
  require('./walk_18.png'),
  require('./walk_19.png'),
];
export const STAND = require('./stand.png') as number;
export const CROSSWALK = require('./crosswalk.png') as number;
