"""Builds the status-rail icons in assets/icons/ui from the source art in assets/icons.

The source figures are black line art on white (walk.gif) or on transparent (stand.png). The app draws on a dark
camera view and tints icons by state, so every output is a white mask whose alpha carries the stroke; React Native's
`tintColor` then colours it. Run from mobile/:  python3 scripts/make_icons.py   (needs Pillow)
"""

from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageSequence

SRC = Path("assets/icons")
OUT = SRC / "ui"
SIZE = 144  # 48 pt at @3x
WALK_FRAMES = 20  # every other frame of the 40-frame source: 12.5 fps reads as smooth walking


def to_mask(img: Image.Image) -> Image.Image:
    """Dark strokes become opaque white; light background becomes transparent."""
    rgba = img.convert("RGBA")
    darkness = rgba.convert("L").point(lambda v: 255 - v)
    # A transparent source keeps its own alpha as the upper bound.
    alpha = ImageChops.darker(darkness, rgba.getchannel("A"))
    mask = Image.new("RGBA", rgba.size, (255, 255, 255, 0))
    mask.putalpha(alpha)
    return mask


def fit(img: Image.Image, size: int = SIZE, pad: float = 0.06) -> Image.Image:
    box = img.getchannel("A").getbbox() or (0, 0, img.width, img.height)
    img = img.crop(box)
    inner = int(size * (1 - 2 * pad))
    scale = inner / max(img.width, img.height)
    img = img.resize((max(1, round(img.width * scale)), max(1, round(img.height * scale))), Image.LANCZOS)
    canvas = Image.new("RGBA", (size, size), (255, 255, 255, 0))
    canvas.alpha_composite(img, ((size - img.width) // 2, (size - img.height) // 2))
    return canvas


def walking_frames() -> list[Image.Image]:
    frames = [to_mask(f) for f in ImageSequence.Iterator(Image.open(SRC / "walk.gif"))]
    # One crop box for all frames, so the figure does not jitter between frames.
    boxes = [f.getchannel("A").getbbox() for f in frames]
    union = (min(b[0] for b in boxes), min(b[1] for b in boxes), max(b[2] for b in boxes), max(b[3] for b in boxes))
    step = len(frames) / WALK_FRAMES
    picked = [frames[int(i * step)].crop(union) for i in range(WALK_FRAMES)]
    return [fit(f) for f in picked]


def crosswalk() -> Image.Image:
    """Zebra stripes seen from the curb: bars that narrow toward the far side of the road."""
    s = SIZE * 4
    img = Image.new("RGBA", (s, s), (255, 255, 255, 0))
    d = ImageDraw.Draw(img)
    near_y, far_y = s * 0.92, s * 0.12
    near_half, far_half = s * 0.47, s * 0.22
    bars = 5
    for i in range(bars):
        # Each bar spans a slice of the road width, in perspective.
        t0, t1 = (2 * i) / (2 * bars - 1), (2 * i + 1) / (2 * bars - 1)
        pts = [
            (s / 2 - near_half + t0 * 2 * near_half, near_y),
            (s / 2 - near_half + t1 * 2 * near_half, near_y),
            (s / 2 - far_half + t1 * 2 * far_half, far_y),
            (s / 2 - far_half + t0 * 2 * far_half, far_y),
        ]
        d.polygon(pts, fill=(255, 255, 255, 255))
    return img.resize((SIZE, SIZE), Image.LANCZOS)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    frames = walking_frames()
    for i, f in enumerate(frames):
        f.save(OUT / f"walk_{i:02d}.png")
    fit(to_mask(Image.open(SRC / "stand.png"))).save(OUT / "stand.png")
    crosswalk().save(OUT / "crosswalk.png")
    lines = [f"  require('./walk_{i:02d}.png')," for i in range(len(frames))]
    (OUT / "index.ts").write_text(
        "// Generated by scripts/make_icons.py from assets/icons/walk.gif and stand.png. Do not edit by hand.\n"
        "export const WALK_FRAMES: number[] = [\n" + "\n".join(lines) + "\n];\n"
        "export const STAND = require('./stand.png') as number;\n"
        "export const CROSSWALK = require('./crosswalk.png') as number;\n"
    )
    print(f"wrote {len(frames)} walk frames, stand, crosswalk to {OUT}")


if __name__ == "__main__":
    main()
